/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stav_ideastreet_test_JniTest */

#ifndef _Included_com_stav_ideastreet_test_JniTest
#define _Included_com_stav_ideastreet_test_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stav_ideastreet_test_JniTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_stav_ideastreet_test_JniTest_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
