/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stav_zhbj_test_Jni */

#ifndef _Included_com_stav_zhbj_test_Jni
#define _Included_com_stav_zhbj_test_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stav_zhbj_test_Jni
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_stav_zhbj_test_Jni_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
